//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Brigader.Module.BusinessObjects.Brigader
{

    public partial class Member : XPLiteObject
    {
        int fId;
        [Key]
        [Persistent(@"id")]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fName;
        [Size(50)]
        [Persistent(@"name")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        string fAddress;
        [Size(35)]
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>("Address", ref fAddress, value); }
        }
        string fMobile;
        [Size(20)]
        public string Mobile
        {
            get { return fMobile; }
            set { SetPropertyValue<string>("Mobile", ref fMobile, value); }
        }
        string fReferee;
        [Size(35)]
        public string Referee
        {
            get { return fReferee; }
            set { SetPropertyValue<string>("Referee", ref fReferee, value); }
        }
        string fRefereemobile;
        [Size(20)]
        [Persistent(@"RefereeMobile")]
        public string Refereemobile
        {
            get { return fRefereemobile; }
            set { SetPropertyValue<string>("Refereemobile", ref fRefereemobile, value); }
        }
        string fSchool;
        [Size(30)]
        public string School
        {
            get { return fSchool; }
            set { SetPropertyValue<string>("School", ref fSchool, value); }
        }
        string fStage;
        [Size(20)]
        [Persistent(@"stage")]
        public string Stage
        {
            get { return fStage; }
            set { SetPropertyValue<string>("Stage", ref fStage, value); }
        }
        string fCourse;
        [Size(20)]
        public string Course
        {
            get { return fCourse; }
            set { SetPropertyValue<string>("Course", ref fCourse, value); }
        }
        string fOccupation;
        [Size(20)]
        public string Occupation
        {
            get { return fOccupation; }
            set { SetPropertyValue<string>("Occupation", ref fOccupation, value); }
        }
        Rank fRankid;
        [Persistent(@"RankId")]
        [Association(@"MemberReferencesRank")]
        public Rank Rankid
        {
            get { return fRankid; }
            set { SetPropertyValue<Rank>("Rankid", ref fRankid, value); }
        }
    }

}
